#!/usr/bin/bash
torchrun \
  --master_addr="localhost" \
  --master_port="12423" \
   --nnodes=1 \
   --nproc_per_node=3 \
train_classifier.py \
    --encoder-type="linformer" \
	--total-epochs=60 \
	--num-layers=6 \
	--batch-size=5 \
	--embed-dim=96 \
	--num-heads=4 \
    --seq-len=65803  \
    --linformer-k=96 \
    --h5-file="/data/ukbb/net_input/genotyped_p1e-1_v2.h5" \
    --test-frac=0.3 \
	--devices=0,1,2 \
    --snapshot-path=/data/ukbb/v2_snapshots/snvformer_currentstuff.pt \
    --warmup-batches=500 \
    --warmup-min-lr=1e-7 \
    --warmup-max-lr=1e-7 \
    --main-scheduler-step-size=1000 \
    --main-scheduler-gamma=1.00 \
    --report-on-batch=20 \
    --no-gradscaler \
    --no-load-encoder \
    --position-encoding=fixed \