#!/usr/bin/bash
torchrun \
   --nnodes=1 \
   --nproc-per-node=4 \
   --max-restarts=0 \
   --rdzv-id=mlp_test \
    --master_addr="localhost" \
  --master_port="12421" \
train_mlp.py \
	--total-epochs=100 \
	--num-layers=2 \
	--batch-size=128 \
	--embed-dim=2 \
    --seq-len=13290 \
    --h5-file="/data/ukbb/net_input/all_gwas.h5" \
    --test-frac=0.3 \
	--devices=0,1,2 \
    --dropout=0.0 \
    --snapshot-path=/data/ukbb/v2_snapshots/script_mlp.pt \
    --warmup-batches=500 \
    --warmup-min-lr=1e-7 \
    --warmup-max-lr=1e-5 \
    --main-scheduler-step-size=1000 \
    --main-scheduler-gamma=0.95 \
    --report-on-batch=100 \
    --no-gradscaler \
