#!/usr/bin/bash
torchrun --standalone --nproc_per_node=3 --master_addr="localhost" train_encoder.py \
    --encoder-type="hyena" \
	--total-epochs=20 \
	--num-layers=8 \
	--batch-size=16 \
	--embed-dim=256 \
	--num-heads=8 \
    --seq-len=13290  \
    --h5-file="/data/ukbb/net_input/all_gwas_v6.h5" \
    --test-frac=0.3 \
	--devices=0,1,2 \
    --snapshot-path=/data/ukbb/v2_snapshots/script_hyena_encoder_all_gwas_learnpos.pt \
    --warmup-batches=500 \
    --warmup-min-lr=1e-10 \
    --warmup-max-lr=1e-7 \
    --main-scheduler-step-size=1000 \
    --main-scheduler-gamma=0.95 \
    --report-on-batch=100 \
    --mask-frac=0.15 \
    --no-gradscaler \
    --no-augment-data \
